spring.application.name=tomo

server.port=8080

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3307/tomo?useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging configuration
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG